### ISSUE TITLE
Use `keccak` SP1 patched crate

### ISSUE THREAD

**Issue by puma314** [moongate-forks/kona#11]
A significant number of cycles are probably due to `keccak`. We can use our patch of `tiny-keccak`: https://docs.succinct.xyz/writing-programs/patched-crates.html and we will probably notice a tremendous savings on the cycle count.

**Comment by zobront** [comment]
@puma314 All the code in Kona uses `alloy_primitives::keccak256` for the hashes. Easy to sub that out in our zkvm_client, but we want it subbed across the whole codebase.

The only easy way I can see to do that without messing with all the Kona code would be to set up an `alloy_primitives` fork that uses the `tiny-keccak` patch, and then patch with that `alloy_primitives` fork.

Do you agree with that approach or have you all found a better way to do this?

**Comment by zobront** [comment]
@puma314 Oh obviously can just patch it. Did it in latest commits on the PR, massively improved benchmarks!

https://github.com/moongate-forks/kona/pull/7/files/19e5b3bc3ae25217286630a4c6b0087da78b2358..6c3217a11cdd574e6db6ef09eafeca06dc9b6d41

Lowered cycles on the derivation from 4bn to under 1bn.
