### ISSUE TITLE
Implement custom hasher for SP1 `PreimageOracle`

### ISSUE THREAD

**Issue by puma314** [moongate-forks/kona#18]
https://www.reddit.com/r/rust/comments/j0fm4x/implementing_a_custom_hash_function/

Since the preimage keys are mostly already random, we should be able to save cycles by implementing a custom hasher that takes the first N bytes of the key and avoid using the default hash function in `HashMap` that is likely expensive in the zkVM.

We will need to profile this to see if this is an improvement, but I suspect it will be.

**Comment by zobront** [comment]
Implemented in #19 and merged into rkyv branch.
