### ISSUE TITLE
Refactor Kona client to have generic oracle

### ISSUE THREAD

**Issue by puma314** [moongate-forks/kona#9]
To prevent a lot of code duplication between `kona_client` and `zkvm_client`, if we refactor the `kona_client` to have a generic for the `oracle` that is used, then we can directly import a lot of their providers and make `WrappingProvider` versions.

The first step is to merge a PR upstream to make the `kona_client` generic (some progress is here: https://github.com/moongate-forks/kona/pull/8/files).

**Comment by zobront** [comment]
PR addressing this is open on upstream Kona: https://github.com/ethereum-optimism/kona/pull/295

Will keep this issue open until it's merged.
